# variables and data
metadata: "data/metadata.tsv"
fastq_dir: "/fast/AG_Landthaler/Projects/WasteWater/data/ww_RNA_all/"
result_dir: "output/"

# reference
reference_kaiju: "/data/landthaler/genome_data/kaiju/nr_euk"
reference_kaiju_name: "nr_euk"

# params
kaiju_params: "-v"

# options
remove_duplicates: TRUE

# qsub params
qsub_default: ""
qsub_kaiju: "-l m_mem_free=200G"
qsub_kaiju_summary: "-l m_mem_free=50G"

# command tools
R: "~/.conda/envs/r-base-4.0/bin/Rscript"
kaiju: "kaiju"
cd-hit-dup: "cd-hit-dup"